### ISSUE TITLE
Error in get_temp_quantiles

### ISSUE THREAD

**Issue by xxguisseppe** [Climandes/ClimIndVis#2]
[ho00000130.txt](https://github.com/Climandes/ClimIndVis/files/4210107/ho00000130.txt)
[stat_list.txt](https://github.com/Climandes/ClimIndVis/files/4210169/stat_list.txt)

I get this error when i run the package for 1 meteorological station **(1965-2018)** with a base period in the **calc_index** of "1981-2010" , and with an "**seasonal**" agregation, especifically in "**December-January-February**" and with the '**tn10p', 'tx10p', 'tn90p', 'tx90p'** indeces i try.

**`Error in apply(temp_base, 1, FUN = zhang_running_qtile, dates_base, qargs$qth,  : 
  dim(X) must have a positive length`**

After debugging all the code i found out that the problem is in:

**`outbase <- apply(temp_base, 1, FUN = zhang_running_qtile, 
    dates_base, qargs$qth, bootstrap_range = bootstrap_range, 
    n = qargs$n, min_fraction = qargs$min_base_fraction, 
    NAmaxQ = qargs$NAmaxQ)`**

Also, when i run the climindvis with a bunch of stations with the same parameters above i get this error:
**`Error in q_temp_inbase[yday_byr, ] : subscript out of bounds`**

These errors only happen when i use the base period 1981-2010 with this especifically season (DJF), but if i change the last yer in base period to **2018** , e.g. like this "1981-2018" or " **any_year** - 2018" i have no error at all. I hope if this is a bug someone could tell me how to fix it.
Thank you.

**Comment by imfeldn** [comment]
Thank you for sharing. We will have a look at this issue as soon as possible.

**Comment by ksedl** [comment]
We have now uploaded a new version and the errors you described above should be fixed. If you still encounter problems, please let us know.
